###服务端口号、服务名
server:
  port: 8080
  application:
    name: user-center
###dubbo配置
dubbo:
  ###dubbo服务名
  application:
    name: user-center
  ###dubbo协议
  protocol:
    name: dubbo
    port: 20880
  ###注册中心地址
  registry:
    address: zookeeper://127.0.0.1:2181
  ###dubbo实现类骚包范围
  scan:
    base-packages: com.liyuan.api.impl